
# Package Overview
package_name: bikeshare_model

# Data Files
training_data_file: bike-sharing-dataset.csv
test_data_file: test.csv

# Variables
target: cnt

pipeline_name: bikeshare_model
pipeline_save_file: bikeshare_model_output_v

features:      # final features to be use
  - season
  - hr
  - holiday
  - workingday
  - weathersit
  - temp
  - atemp
  - hum
  - windspeed
  # generated in pre-processeing
  - yr            
  - mnth
  - weekday_Fri
  - weekday_Mon
  - weekday_Sat
  - weekday_Sun
  - weekday_Thu
  - weekday_Tue
  - weekday_Wed

unused_fields:  # Features to drop before pipeline
  - dteday
  - weekday
  - casual
  - registered

# Features inside processing pipeline

date_var: dteday
weekday_var: weekday
weathersit_var: weathersit

year_var: yr
month_var: mnth
season_var: season
holiday_var: holiday
workingday_var: workingday
hour_var: hr

temp_var: temp
atemp_var: atemp
humidity_var: hum
windspeed_var: windspeed

# ordinal order after looking at target column sum in training data

year_mappings:
  2011: 0
  2012: 1

month_mappings:     
  January: 0
  February: 1
  March: 3
  April: 5
  May: 7
  June: 9
  July: 10
  August: 11
  September: 8
  October: 6
  November: 4
  December: 2

season_mappings:
  spring: 0
  winter: 1
  summer: 2
  fall: 3

weather_mappings:
  Heavy Rain: 0
  Light Rain: 1
  Mist: 2
  Clear: 3

holiday_mappings:
  Yes: 0
  No: 1

workingday_mappings:
  Yes: 1
  No: 0

hour_mappings:
  4am: 0
  3am: 1
  5am: 2
  2am: 3
  1am: 4
  12am: 5
  6am: 6
  11pm: 7
  10pm: 8
  10am: 9
  9pm: 10
  11am: 11
  7am: 12
  9am: 13
  8pm: 14
  2pm: 15
  1pm: 16
  12pm: 17
  3pm: 18
  4pm: 19
  7pm: 20
  8am: 21
  6pm: 22
  5pm: 23

# set train/test split
test_size: 0.20

# to set the random seed
random_state: 42
# alogrithm parameters
n_estimators: 100
max_depth: 10
